### ISSUE TITLE
Site blocked @ SFHS

### ISSUE THREAD

**Issue by TheDonk113** [Wade7wastaken/Website#13]
IT might be on to you idk if you know about it or what you can do but regardless it is blocked at the moment, they marked you as security.proxy and not a custom blocklist which is reassuring at least

**Comment by Wade7wastaken** [comment]
Yeah, I know. I have plans to have multiple hosts, so the site can be accessed from multiple domains. I am currently waiting for the next release of NextJS, which has some features that will help me with this. I'll close this issue when that's done.

**Comment by Wade7wastaken** [comment]
Completed. There are now 4 (maybe 5) active mirrors that work at sfhs
